version: 1.0.{build}
image: Visual Studio 2019
configuration: Release

build_script:
  - generate.bat
  - msbuild brickstone.sln

pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master